import LegalLayout from './LegalLayout'

export default function AUP({ onBack }) {
  return <LegalLayout eyebrow="LEGAL / 03" title="Acceptable Use Policy" onBack={onBack}>
    <section><h2>1. Purpose</h2><p>This Policy protects the bulletin board as a lawful, respectful place for students to exchange physical textbooks. It applies to accounts, profiles, usernames, listings, photos, reviews, messages, reactions, reports, and any other use of the service.</p></section>
    <section><h2>2. Permitted listings</h2><p>Listings must concern lawfully owned physical textbooks or directly related physical course materials. Information about title, ISBN, edition, condition, access-code status, price, ownership, and availability must be honest and reasonably complete. Listings may remain hidden until manually approved.</p></section>
    <section><h2>3. Prohibited items and content</h2><p>Do not offer PDFs, e-books, scans, copied course packs, unauthorized test banks, stolen goods, counterfeit goods, separately sold credentials, malware, regulated or illegal goods, or anything that infringes copyright or another person’s rights. Do not place prohibited content in images, usernames, profile fields, links, or messages.</p></section>
    <section><h2>4. Account and identity integrity</h2><p>Do not impersonate another person or institution, create deceptive accounts, misrepresent school affiliation, evade a suspension, share accounts, or use an inappropriate or misleading username. Do not collect or expose another user’s personal information without authorization.</p></section>
    <section><h2>5. Marketplace conduct</h2><p>No fraud, bait pricing, advance-fee schemes, fake listings, coordinated manipulation, review trading, unsolicited advertising, or attempts to move users into suspicious payment arrangements. Do not mark an item available when it is sold or intentionally conceal material defects.</p></section>
    <section><h2>6. Communications</h2><p>Messages must relate to legitimate marketplace activity. Harassment, threats, hate speech, sexual content, intimidation, repeated unwanted contact, phishing, spam, malicious links, and pressure to send advance payment are prohibited. Reactions and reviews must not be used to target or humiliate another user.</p></section>
    <section><h2>7. Technical misuse</h2><p>Do not scrape, crawl, index, reverse engineer, probe, overload, interfere with, or bypass the service or its security controls. Automated account creation, bulk messaging, credential testing, malicious code, unauthorized API access, and attempts to access another user’s data are prohibited.</p></section>
    <section><h2>8. Safety expectations</h2><p>Arrange exchanges in public, well-lit places such as staffed campus buildings. Inspect the item before paying, avoid carrying unnecessary cash, tell someone about the meeting, and leave if the situation feels unsafe. Never use the service to arrange dangerous, coercive, or unlawful activity.</p></section>
    <section><h2>9. Reviews</h2><p>Reviews must reflect a genuine interaction and your honest experience. They must be relevant, proportionate, and free of private information, retaliation, extortion, discrimination, or knowingly false claims. Reviews may be edited by their authors, moderated, rejected, or removed.</p></section>
    <section><h2>10. Reports</h2><p>Use reporting tools for suspected scams, harassment, prohibited content, or safety concerns. Reports must be made in good faith. A report may preserve account details and the relevant chat transcript for moderator review. False, retaliatory, or abusive reporting is prohibited.</p></section>
    <section><h2>11. Enforcement</h2><p>MyStudentBulletin may reject, limit, hide, preserve, or remove content and may warn, restrict, suspend, or terminate users. Factors may include severity, context, prior conduct, safety risk, available evidence, and legal obligations. Enforcement may occur without prior notice where reasonably necessary. Approval or lack of enforcement does not endorse content or guarantee safety.</p></section>
    <section><h2>12. Cooperation and appeals</h2><p>Users must reasonably cooperate with legitimate safety or moderation inquiries. You may contact support@mystudentbulletin.ca to request review of a moderation decision. Submission of an appeal does not suspend the decision, and repeated or abusive appeals may be disregarded.</p></section>
  </LegalLayout>
}
