import LegalLayout from './LegalLayout'

export default function Privacy({ onBack }) {
  return <LegalLayout eyebrow="LEGAL / 02" title="Privacy Policy" onBack={onBack}>
    <section><h2>1. Scope and accountability</h2><p>This Policy explains how personal information is collected, used, disclosed, retained, and protected when you use MyStudentBulletin. The service aims to follow applicable Canadian privacy requirements, including Alberta’s Personal Information Protection Act where it applies. Privacy questions may be directed to the contact address below.</p></section>
    <section><h2>2. Information collected</h2><p>Account information may include your name, username, email, authentication provider, school, profile photo, account identifiers, and settings. Marketplace information includes listings, photos, ISBNs, course details, prices, status, reviews, and approvals. Communications information includes chats, reactions, edits, reports, moderation decisions, and report transcripts. Technical information may include timestamps, browser or device information, network information, logs, error records, and security events.</p></section>
    <section><h2>3. Sources and consent</h2><p>Information is collected directly from you, from authentication providers you choose, through your use of the service, and from other users who communicate with or report you. By providing information and using the service, you consent to reasonable collection, use, and disclosure for the purposes described here, subject to rights and exceptions under applicable law.</p></section>
    <section><h2>4. Purposes</h2><p>Information is used to create and secure accounts, display profiles and listings, enable messaging, verify uniqueness, moderate content, approve listings and reviews, investigate reports, prevent fraud and abuse, provide support, enforce policies, maintain records, troubleshoot errors, improve reliability, comply with legal obligations, and protect users or the public.</p></section>
    <section><h2>5. Public and user-visible information</h2><p>Approved profile information, usernames, school, profile photos, listings, ratings, reviews, and selling history may be visible to authenticated users. Messages are visible to conversation participants and may be included in a report transcript reviewed by authorized moderators. Do not post information you do not want shared in these ways.</p></section>
    <section><h2>6. Service providers and processing locations</h2><p>Firebase, Google Cloud, hosting providers, authentication providers, and other contractors may process information on behalf of the service. Information may be stored or accessed outside Alberta or Canada and may be subject to lawful access by authorities in those jurisdictions. Providers receive information only as reasonably needed to supply, secure, or support their services.</p></section>
    <section><h2>7. Disclosure</h2><p>Personal information is not sold or rented. It may be disclosed with your consent, to service providers, during a business reorganization or transfer, to investigate abuse or security incidents, to enforce agreements, to collect a debt, to protect rights or safety, or where permitted or required by law, court order, or lawful authority.</p></section>
    <section><h2>8. Reports and moderation records</h2><p>Reports may contain the reporter’s identity, the reported user’s identity and email, listing information, reasons, timestamps, message context, and a chat transcript. These records may be reviewed by authorized administrators and retained where reasonably necessary for safety, repeat-abuse prevention, dispute handling, legal compliance, and enforcement. Reports should be made honestly and only for legitimate safety or policy concerns.</p></section>
    <section><h2>9. Retention and deletion</h2><p>Information is retained only as long as reasonably needed for the purposes described, legal obligations, backups, security, fraud prevention, dispute resolution, and enforcement. Account deletion may not immediately remove backups, de-identified information, transaction-related records, or records needed to investigate abuse. When information is no longer reasonably required, it will be deleted, anonymized, or securely disposed of where practicable.</p></section>
    <section><h2>10. Safeguards</h2><p>Reasonable administrative, technical, and organizational safeguards are used based on the sensitivity of the information. These may include authentication, access controls, security rules, restricted admin access, logging, and provider safeguards. No online system is completely secure, and absolute security cannot be guaranteed. You are responsible for protecting your password and devices.</p></section>
    <section><h2>11. Access, correction, and consent choices</h2><p>You may update available profile fields in the service. Subject to applicable law, you may request access to or correction of personal information, ask questions about its use or disclosure, or withdraw consent for optional processing. Withdrawal may limit or prevent continued use of features. Identity verification may be required before fulfilling a request.</p></section>
    <section><h2>12. Account deletion and complaints</h2><p>Requests for account deletion or privacy concerns may be sent to support@mystudentbulletin.ca. Provide enough information to identify the account, but do not email passwords or unnecessary sensitive information. If a concern is not resolved, you may have the right to contact the Office of the Information and Privacy Commissioner of Alberta or another applicable regulator.</p></section>
    <section><h2>13. Minors</h2><p>The service is not intended for unsupervised use by children. A user below the age of majority must have permission and supervision from a parent or legal guardian. If personal information was submitted without appropriate authorization, contact support to request review and deletion.</p></section>
    <section><h2>14. Policy changes</h2><p>This Policy may change as features, providers, or legal requirements evolve. Material changes will be communicated through the service or another reasonable method. The date above identifies the current version.</p></section>
  </LegalLayout>
}
