import LegalLayout from './LegalLayout'

export default function ToS({ onBack }) {
  return <LegalLayout eyebrow="LEGAL / 01" title="Terms of Service" onBack={onBack}>
    <section><h2>1. Acceptance and eligibility</h2><p>By creating an account, accessing the service, or posting content, you agree to these Terms and the Acceptable Use Policy. You must be legally capable of entering this agreement. If you are under the age of majority where you live, you may use the service only with the permission and supervision of a parent or legal guardian who accepts these Terms on your behalf.</p></section>
    <section><h2>2. Bulletin board only</h2><p>MyStudentBulletin provides a venue for users to discover listings and communicate. It is not a retailer, broker, auctioneer, payment processor, shipping provider, educational institution, representative, fiduciary, or agent of any user. It does not own, possess, inspect, authenticate, price, deliver, insure, or guarantee any item. No employment, partnership, joint venture, franchise, or agency relationship is created.</p></section>
    <section><h2>3. Transactions are between users</h2><p>Users negotiate and complete transactions entirely at their own risk. You are solely responsible for confirming identity, legal ownership, edition, ISBN, condition, access-code status, price, suitability, and authenticity before exchanging money. MyStudentBulletin is not a party to any transaction and has no duty to resolve refunds, chargebacks, delivery failures, tax obligations, ownership disputes, or disagreements between users.</p></section>
    <section><h2>4. Account responsibility</h2><p>You must provide accurate information, protect your credentials, and promptly report suspected unauthorized access. You are responsible for activity conducted through your account. Usernames may be removed if misleading, impersonating, offensive, or otherwise inappropriate. You may not sell, transfer, share, or automate access to an account.</p></section>
    <section><h2>5. Listings and user content</h2><p>You retain ownership of content you submit. You grant MyStudentBulletin a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, format, display, and moderate that content only as reasonably needed to operate, secure, promote, and improve the service. You represent that you have all rights needed to post the content and that it is accurate, lawful, and does not infringe copyright, privacy, publicity, trademark, or other rights.</p></section>
    <section><h2>6. Prohibited material and conduct</h2><p>Digital textbooks, PDFs, e-books, copied course materials, unauthorized access codes, stolen goods, counterfeit items, malware, spam, scraping, fraud, impersonation, harassment, threats, discrimination, and attempts to evade moderation are prohibited. Physical textbooks must be lawfully owned and accurately described. Copyrighted content remains subject to Canada’s Copyright Act and other applicable law.</p></section>
    <section><h2>7. Moderation and availability</h2><p>Listings and reviews may require approval. MyStudentBulletin may investigate reports, retain relevant records, reject or remove content, limit features, suspend accounts, or terminate access at any time when reasonably necessary for safety, compliance, or service integrity. Moderation is not a guarantee that content or users are accurate, lawful, or safe. The service may be changed, interrupted, or discontinued without guarantee of notice or availability.</p></section>
    <section><h2>8. Safety</h2><p>Meet in a public, well-lit location, inspect the physical item before paying, tell someone where you are going, and never send advance payment to an unverified person. Users assume the risks of in-person meetings and transactions. Contact emergency services if you believe anyone is in immediate danger.</p></section>
    <section><h2>9. Third-party services</h2><p>The service depends on providers such as Firebase, Google Cloud, authentication providers, hosting platforms, browsers, and networks. Their terms and privacy practices may apply separately. MyStudentBulletin is not responsible for third-party outages, security incidents, content, or acts beyond its reasonable control.</p></section>
    <section><h2>10. Disclaimer of warranties</h2><p>To the maximum extent permitted by law, the service is provided “as is” and “as available.” MyStudentBulletin disclaims all express, implied, statutory, and collateral warranties, including merchantability, fitness for a particular purpose, title, non-infringement, accuracy, security, availability, and course suitability. No statement creates a warranty unless expressly stated in writing.</p></section>
    <section><h2>11. Release and limitation of liability</h2><p>To the maximum extent permitted by law, you release MyStudentBulletin and its operators, affiliates, contractors, and representatives from claims arising from user conduct, listings, transactions, meetings, payments, items, or disputes. They will not be liable for indirect, incidental, special, exemplary, punitive, or consequential loss, loss of data, lost opportunity, personal injury caused by another user, or property damage arising from the service. Where liability cannot lawfully be excluded, aggregate liability will be limited to the greater of CAD $100 and the amount you paid directly to MyStudentBulletin during the previous twelve months. Nothing excludes liability that cannot legally be excluded.</p></section>
    <section><h2>12. Indemnity</h2><p>To the maximum extent permitted by law, you will defend, indemnify, and hold harmless MyStudentBulletin and its operators from third-party claims, damages, penalties, costs, and reasonable legal fees arising from your content, listings, transactions, conduct, breach of these Terms, or violation of another person’s rights. This obligation does not apply to the extent a claim was caused by conduct for which indemnity cannot lawfully be required.</p></section>
    <section><h2>13. Governing law and disputes</h2><p>These Terms are governed by the laws of Alberta and the federal laws of Canada applicable there, without regard to conflict-of-law principles. Subject to any mandatory consumer right, the courts located in Alberta will have exclusive jurisdiction. Before starting a claim, you agree to provide written notice and allow thirty days for an informal resolution attempt.</p></section>
    <section><h2>14. General terms</h2><p>If any provision is unenforceable, it will be limited or removed only to the minimum extent necessary, and the remainder will continue. Failure to enforce a provision is not a waiver. You may not assign this agreement without consent. MyStudentBulletin may assign it as part of a reorganization, transfer, or sale. These Terms, the Privacy Policy, and the Acceptable Use Policy form the entire agreement regarding the service.</p></section>
    <section><h2>15. Changes and termination</h2><p>These Terms may be updated as the service evolves. Material changes will be communicated through the service or another reasonable method. Continued use after the effective date means acceptance of the revised Terms. You may stop using the service at any time. Provisions intended by their nature to survive termination, including ownership, releases, liability limits, indemnity, and dispute terms, will survive.</p></section>
  </LegalLayout>
}
